### ISSUE TITLE
Could not create paste: Error saving paste. Sorry.

### ISSUE THREAD

**Issue by zamunda68** [PrivateBin/PrivateBin#1122]
## Steps to reproduce

1. Open the PrivateBin web UI
2. Click on the blue "Send" button

### What happens
 Could not create paste: Error saving paste. Sorry.

### What should happen
There should be a link generated to the paste 

## Basic information

**Server OS: Rocky Linux 9.2**

**Webserver: NGINX 1.20.1**

**Browser: Chrome 114**

**PrivateBin version: 1.5.2**

I can reproduce this issue on <https://privatebin.net>: Yes / No
No

**Comment by ppfeufer** [comment]
If this is by any chance a fresh Docker installation, see here (scroll down to "Fix Permissions") » https://ppfeufer.de/privatebin-your-self-hosted-pastebin-instance/

**Comment by zamunda68** [comment]
It is not a Docker container installation, it is running inside a virtual machine, on the guest OS of the virtual machine itself.

**Comment by zamunda68** [comment]
Does the application have any logs I can check? I am having a hard time debugging even with [strace](https://man7.org/linux/man-pages/man1/strace.1.html).

**Comment by ppfeufer** [comment]
Still, check the file permissions.

**Comment by fitzg2** [comment]
@zamunda68  Nginx error logs clearly

**Comment by zamunda68** [comment]
Lads, I found it - it was the SELinux. As soon as I set it to "permissive", the issue was resolved. 

The command I used to set it to permissive:

`setenforce 0`

I will adjust its configuration. 

Thank you for your help!

**Comment by rugk** [comment]
Just FYI: SeLinux is a security feature. By disabling it you are disabling a security feature of your OS.

This guide in our wiki may help and have some setup tips: https://github.com/PrivateBin/PrivateBin/wiki/Installation-on-Red-Hat-with-SELinux

**Comment by fitzg2** [comment]
This happens to me without SELinux. Same error still going on

> 2023/08/18 13:28:18 [error] 153573#153573: *195337 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Exception: A JSON error occurred: Syntax error (4) in /var/www/html/pbin/lib/Json.php:76

Stack trace:
#0 /var/www/html/pbin/lib/Json.php(52): PrivateBin\Json::_detectError()
#1 /var/www/html/pbin/lib/Data/Filesystem.php(350): PrivateBin\Json::decode()
#2 /var/www/html/pbin/lib/Data/Filesystem.php(113): PrivateBin\Data\Filesystem->_get()
#3 /var/www/html/pbin/lib/Data/Filesystem.php(373): PrivateBin\Data\Filesystem->read()
#4 /var/www/html/pbin/lib/Data/AbstractData.php(158): PrivateBin\Data\Filesystem->_getExpiredPastes()
#5 /var/www/html/pbin/lib/Model.php(72): PrivateBin\Data\AbstractData->purge()
#6 /var/www/html/pbin/lib/Controller.php(253): PrivateBin\Model->purge()
#7 /var/www/html/pbin/lib/Controller.php(125): PrivateBin\Controller->_create()
#8 /var/www/html/pbin/index.php(18): PrivateBin\Controller->__construct()
#9 {main}
  thrown in /var/www/html/pbin/lib/Json.php on line 76" while reading response header from upstream, client: w.x.y.z, server: pastebin.lexul.dev, request: "POST / HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "pastebin.lexul.dev"

**Comment by elrido** [comment]
@fitzg2 The JSON encoding error means that the message sent by the client to the server got mangled before it could reach the PHP logic. We try and document all the factors that commonly contribute to this in:
https://github.com/PrivateBin/PrivateBin/wiki/Configuration#sizelimit

Beyond those settings in the web- and php service, it can also occur if you use some kind of caching or loadbalancing service in front of your PrivateBin instance. You will have to carefully review your setup of each component in the stack to eliminate each possibility.

Likely duplicate of #263, #853, #858

**Comment by fitzg2** [comment]
It has nothing to do with size as the request is very small.

`{"adata":[["RNP6g82Supr8eyquLzA4Qg==","lhV+sJMZrHk=",100000,256,128,"aes","gcm","zlib"],"plaintext",0,0],"meta":{"expire":"1week"},"v":2,"ct":"mlIdSUqLJyBX1UVb1PrPemnIYxp5T3yxx7lsJVMXVkMvaQ=="}`

**Comment by d03j** [comment]
> If this is by any chance a fresh Docker installation, see here (scroll down to "Fix Permissions") » https://ppfeufer.de/privatebin-your-self-hosted-pastebin-instance/

FWIW - I stumbled here because I had the same mistake and am testing privatebin on a rootless container (podman). I solved it by changing the ownership of my data and config dirs to 165533:100081 which is probably a more secure solution than making it globally writable and executable (777). ;)

```
# checking container's user
$ podman exec -ti privatebin /bin/sh
/var/www $ whoami
nobody
/var/www $ id
uid=65534(nobody) gid=82(www-data)

# checking subuid map
$ cat /etc/subuid
myuser:100000:65536

# changing ownership
$ sudo chown 165533:100081 /path/to/privatebin/mounts/*

```
