### ISSUE TITLE
Call to undefined function PrivateBin\Data\opcache_invalidate() in /usr/local/www/privatebin/lib/Data/Filesystem.php:284

### ISSUE THREAD

**Issue by dlangille** [PrivateBin/PrivateBin#1678]
I suspect this is a missing dependency, but I don't know which one. Did I miss something in release notes? List of deps?

**Did you use the FAQ section?**
- [x] Yes, I have read [the FAQ](https://github.com/PrivateBin/PrivateBin/wiki/FAQ) and I found no solution/answer there.

## Steps to reproduce

1. Create a new paste

### What happens
error on page:  Could not create document: server error or not responding

error in logs: 2025/10/12 12:39:33 [error] 82976#595035: *3 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function PrivateBin\Data\opcache_invalidate() in /usr/local/www/privatebin/lib/Data/Filesystem.php:284

### What should happen
new paste should be created
no errors in log

FreeBSD 14.3

nginx-1.28.0_3,3

**Browser:**

2.0.1

I can reproduce this issue on <https://privatebin.net>: No

**Comment by elrido** [comment]
That would be the [Opcache](https://www.php.net/manual/en/opcache.installation.php) module. Caused by 6054e99849608b2ca1de9a1a0fc799e4c53a6b1b which I had added when testing the release and discovering the opcache would interfere with the traffic limiter when using the Filesystem backend. I was baffled it had gone unnoticed before and in unit testing.

**Comment by dlangille** [comment]
I'll treat very soon. Thanks for the lead.

**Comment by dlangille** [comment]
FIxed here by including opcache in the PHP modules.  See `USE_PHP` here:

https://cgit.freebsd.org/ports/commit/?id=31de9349dc8166a765a2919606074a4cc5c25019

Thank you. Working fine here.

**Comment by rugk** [comment]
Keeping it open for merge of #1679, a downstream fix does not fix it here upstream of course so…
